version: "3"
services:
    db:
        image: mongo
        expose:
            - "27017"
        volumes:
            - kiddyup-mongodb_data_container:/data/db
        ports:
            - "27017:27017"
volumes:
    kiddyup-mongodb_data_container:
